# Generated by Django 6.0.7 on 2026-07-25 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0003_instance_lease_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='provider_id 须以小写字母开头，1–64 位，仅含小写字母、数字、连字符', regex='^[a-z][a-z0-9-]{0,63}$')])),
                ('api', models.CharField(choices=[('openai-completions', 'openai-completions'), ('anthropic-messages', 'anthropic-messages')], max_length=32)),
                ('base_url', models.CharField(max_length=512)),
                ('api_key_env_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='apiKey env id 须大写字母开头，仅含大写字母、数字、下划线', regex='^[A-Z][A-Z0-9_]{0,127}$')])),
                ('auth_header', models.BooleanField(default=True)),
                ('models_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_providers', to='containers.instance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'provider_id'), name='unique_instance_provider_id')],
            },
        ),
    ]
