# Generated by Django 6.0.7 on 2026-07-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0003_instance_lease_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('public_key_pem', models.TextField(blank=True, default='')),
                ('private_key_pem', models.TextField(blank=True, default='')),
                ('device_token', models.CharField(blank=True, default='', max_length=255)),
                ('scopes_json', models.TextField(blank=True, default='[]')),
                ('pairing_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('unpaired', 'unpaired'), ('pending', 'pending'), ('paired', 'paired'), ('error', 'error')], default='unpaired', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing', to='containers.instance')),
            ],
        ),
    ]
