# Generated by Django 6.0.7 on 2026-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='attempt_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
