# Generated by Django 6.0.7 on 2026-07-24 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='name 须以小写字母开头，3–30 位，仅含小写字母、数字、连字符', regex='^[a-z][a-z0-9-]{2,29}$')])),
                ('port', models.IntegerField()),
                ('token', models.CharField(max_length=127)),
                ('home_dir', models.CharField(max_length=512)),
                ('container_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('creating', 'creating'), ('running', 'running'), ('stopped', 'stopped'), ('removing', 'removing'), ('error', 'error')], default='creating', max_length=16)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
